const categories = [
    {
        "id": "all",
        "name": "الكل"
    },
    {
        "id": "photography",
        "name": "التصوير"
    },
    {
        "id": "home",
        "name": "المنزل"
    },
    {
        "id": "camping",
        "name": "التخييم والصيد"
    },
    {
        "id": "clothing",
        "name": "الأحذية والملابس"
    },
    {
        "id": "pc",
        "name": "الكمبيوتر والإنتاجية"
    }
];

const products = [
    {
        "id": 1790880004628,
        "title": "حذاء خيالي من اديداس adidas Ultra Boost 21",
        "price": "50000",
        "originalPrice": "300000",
        "currency": "د.ع",
        "category": "clothing",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://images.stockx.com/images/adidas-Ultra-Boost-21-Argentina-National-Soccer-Team.jpg?fit=fill&bg=FFFFFF&w=576&h=384&q=57&dpr=2&trim=color&updated_at=1626188079",
        "description": "ء adidas UltraBoost 21 Argentina National Soccer Team (كود الموديل: GZ7120) هو إصدار خاص ومحدود نزل بنهاية عام 2021 احتفالاً وتكريماً لمنتخب الأرجنتين لكرة القدم.\nوهذه هي المواصفات الفنية والتصميمية الكاملة للحذاء باللهجة العراقية:\nالألوان والهوية الرسمية\n• الألوان (Colorway): يجي بدمج رهيب يمثل ألوان علم الأرجنتين: الأبيض الأساسي (Cloud White)، الأزرق السماوي (Clear Blue)، والكحلي الداكن (Night Indigo).\n• الشعار الرسمي: يحمل شعار الاتحاد الأرجنتيني لكرة القدم (AFA) بشكل بارز ومطرز على لسان الحذاء، حتى يعطيك الهوية الرياضية الكاملة للمنتخب.\nالمواصفات الفنية والتقنية\n• العلويات (adidas Primeknit+): الجزء العلوي مصنوع من قماش الحياكة المطوّر اللي يقعد على الرجل مثل الجواريب (Sock-like fit)، ويوفر تهوية ممتازة ومرونة عالية للحركة.\n• نعل البوست الارتدادي (Boost Midsole): النعل مجهز بتقنية البوست المشهورة من أديداس، وبنسخة الـ 21 تم زيادة كمية الفوم بنسبة 6% إضافية مقارنة بالموديلات السابقة، مما يعطي راحة خيالية وامتصاص قوي للصدمات مع كل خطوة.\n• نظام التوجيه (adidas LEP): يحتوي على نظام التيرشن الجديد (Linear Energy Push)، اللي يزيد من صلابة مقدمة القدم بنسبة 15%، حتى يعطيك دفع وارتداد أسرع أثناء الركض أو المشي.\n• النعل السفلي (Continental™ Rubber): النعل الخارجي مصنوع من مطاط شركة \"كونتيننتال\" العالمية للسيارات بتصميم Stretchweb، حتى يضمن لك ثبات ومقاومة عالية للانزلاق على مختلف الأسطح.\nالوزن والقياسات الهندسية\n• الوزن: يزن الحذاء حوالي 340 غرام (أو 11.9 أونصة)، وهو متوازن جداً كحذاء ركض يومي مريح أو كاجوال.\n• فرق الارتفاع (Midsole Drop): يجي بفرق 10 ملم بين الكعب والمقدمة (ارتفاع الكعب 30.5 ملم / مقدمة القدم 20.5 ملم).",
        "url": "https://stockx.com/adidas-ultra-boost-21-argentina-national-soccer-team",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 1
    },
    {
        "id": 1790877912822,
        "title": "Inkbird 4-Probe Wireless Meat Thermometer BBQ Gloves Three-Mode WiFi Bluetooth مقياس حرارة ",
        "price": "50000",
        "originalPrice": "200000",
        "currency": "د.ع",
        "category": "camping",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://i.ebayimg.com/images/g/QqAAAeSwdCto7wuI/s-l1600.webp",
        "description": "هذا الجهاز يجي ويا 4 أشياش (مجسات) لاسلكية بالكامل وميزته الرهيبة إنه يشتغل بـ 3 طرق ربط بنفس الوقت (واي فاي 2.4GHz، بلوتوث 5.4، ووضع أوفلاين بدون نت).\n✨ أهم الميزات والمواصفات:\n• يشتغل بكل مكان (3 أنظمة ربط): تكدر تربطه على واي فاي البيت وتراقب اللحم وأنت طالع، أو على البلوتوث (يوصل مداه لـ 90 متر)، وإذا رحت لـ البر أو المزرعة وماكو نت، يشتغل عادي (أوفلاين) ويحفظ القراءات بالجهاز نفسه.\n• 4 أشياش ضد المي: الأشياش لاسلكية تماماً ومقاومة للمي (IP67) وتكدر تغسلها بغسالة المواعين. كل شيش بيه مستشعرين: واحد يقيس حرارة اللحم الداخلية (من 10 إلى 100 مئوية) والثاني يقيس حرارة المنقلة أو التندور (من 0 إلى 300 مئوية).\n• شحن سريع وباتري قوي: تشحن الشيش لمدة 25 دقيقة بس، يشتغل وياك 25 ساعة متواصلة! وقاعدة الشحن الأساسية هم بيها باتري قوي يتشحن.\n• تطبيق ذكي يخبل: التطبيق يجي بيه 26 منيو جاهز لحرارة اللحوم حسب تصنيف الـ USDA، وتكدر تخلي بيه منبه إذا صعدت الحرارة أو نزلت، وهم يشتغل على ساعة آبل (Apple Watch).\n• كفوف شواء مجانية: يجي وياه بالباكيت كفوف (قماصل) حرارية قوية علمود تلزم بيها المشبج واللحم الحار بدون ما تحترك إيدك.\nالجهاز فد شي راقي ومثالي لعزائم القوزي، البريسكيت، والمشويات العراقية الثقيلة!",
        "url": "https://i.ebayimg.com/images/g/QqAAAeSwdCto7wuI/s-l1600.webp",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 1
    },
    {
        "id": 1790879102838,
        "title": "Holoswim 2S Smart Swim Goggles, Digital Real-time Display AR Goggles  نظارات سباحة خرافية",
        "price": "70000",
        "originalPrice": "150000",
        "currency": "د.ع",
        "category": "camping",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://m.media-amazon.com/images/I/71kddRk-EvL._AC_SX522_.jpg",
        "description": "مناظير السباحة الذكية Holoswim 2S هي نظارات سباحة متطورة تدعم تقنية الواقع المعزز (AR) ومخصصة لتتبع الأداء الرياضي داخل المي.\nوهذه هي أبرز مواصفات ومميزات النظارة باللهجة العراقية:\nالشاشة والعرض (AR Display)\n• شاشة مدمجة بالعدسة: تعرض لك معلومات حية ومباشرة كدام عينك وأنت تسبح (مثل الوقت، الأمتار، الجولات، والسرعة) بدون ما تحتاج توقف وتشوف ساعتك.\n• تقنية متطورة: تستخدم نظام (AR Holographic Waveguide) وبدقة وضوح 128×64 بكسل بشاشة أحادية اللون (ماتريكس أخضر) وزاوية رؤية 25 درجة حتى تشوف الأرقام بوضوح عالي تحت المي.\nالذكاء الاصطناعي والتتبع\n• حساس حركة سداسي المحاور: بيه مستشعر (IMU 6-axis) ويا خوارزميات ذكاء اصطناعي ذكية، تحسب وتعرف 12 مؤشر مختلف للسباحة، مثل نوع السحبة (الستروك)، الـ SWOLF، والسرعة، وبدقة توصل لـ 99.8%.\n• تطبيق Holosport: النظارة تتزامن ويا تطبيق Holosport ع التلفون بعد ما تخلص سباحة، حتى يطلعلك تقرير كامل وتحليل لأدائك، وتكدر تخلي أهداف معينة لتمارينك.\nالتصميم والبطارية\n• الوزن والراحة: وزنها خفيف تقريباً 70 غرام، وتجي وياها 4 قطع لجسر الأنف (Nose bridges) بأحجام مختلفة (S, M, L, XL) حتى تقعد فيت ومريحة على أي وجه وما تعبر مي.\n• مقاومة المي والضباب: مقاومة للمي بمعيار قوي جداً (IPX8 / IP68)، والعدسات مالتها مغلفة بطبقة نانو ضد الضباب حاصلة على شهادة TÜV، يعني ما تغوش العين حتى لو انحكت أكثر من 1000 مرة.\n• البطارية والشحن: بيها بطارية ليثيوم بسعة 70mAh تطول وياك حد 4 ساعات استخدام متواصل، وتنشحن عن طريق كابل مغناطيسي مريح يطول حوالي ساعتين حتى يقبط شحن.\nميزات إضافية\n• بدون اشتراكات: كل ميزات الذكاء الاصطناعي وتتبع البيانات مجانية بالكامل ومحفوظة إلك بدون أي اشتراك شهري.\n• تشتغل بالمي المفتوح: تكدر تربطها بساعات ذكية مثل ساعات Garmin أو Apple Watch حتى تعرضلك البيانات وتشتغل وياك حتى بالبحيرات أو البحار (المي المفتوح).",
        "url": "https://m.media-amazon.com/images/I/71kddRk-EvL._AC_SX522_.jpg",
        "condition": "used",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 2
    },
    {
        "id": 1790877628571,
        "title": "Q10 Smart Ear Canal Detector, SEALED - New in Box كبس فاحص اذن ",
        "price": "30000",
        "originalPrice": "50000",
        "currency": "د.ع",
        "category": "home",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://s.alicdn.com/@sc04/kf/H73cb9c960a1c47c087d09da8e38247a3z.jpg?avif=close&webp=close",
        "description": "كاشف ذكي مع شاشة (Q10) - منظار تنظيف الأذن 1080P HD\n🔍 الآن العناية بالأذن تتم بسهولة فائقة\n✨ المميزات:\n✅ شاشة عرض مدمجة - bina mobile connect kiye مشاهدة مباشرة.\n✅ عدسة 1080P HD - صورة/فيديو واضح.\n✅ خيار التقاط الصور ومقاطع الفيديو.\n✅ تصميم آمن مع نصائح صديقة للأذن.\n✅ قابل لإعادة الشحن ومحمول.",
        "url": "https://s.alicdn.com/@sc04/kf/H73cb9c960a1c47c087d09da8e38247a3z.jpg?avif=close&webp=close",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 3
    },
    {
        "id": 1790877355777,
        "title": "Fifine microphone A6V مايك فيفاين ",
        "price": "35000",
        "originalPrice": "55000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://fifinemicrophone.com/cdn/shop/files/FIFINEAmpliGameA6VUSBRGBMicrophoneforGaming.jpg?v=1767063753&width=1100",
        "description": "For flawless broadcasts? Get FIFINE AmpliGame A6V USB condenser microphone! Vibrant RGB, a pop filter, built-in shock mount, gain control, and a sturdy tripod stand keep your gaming and streaming voice natural, stable, and confidently precise.",
        "url": "https://fifinemicrophone.com/cdn/shop/files/FIFINE-A6V-microphone-black-left.png?v=1767063492&width=1100",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 4
    },
    {
        "id": 1790816049556,
        "title": "CHAOMIN Inverter 12v to 110v,6000W Pure Sine Wave Power Inverter Dc 12V to 220V,",
        "price": "60000",
        "originalPrice": "120000",
        "currency": "د.ع",
        "category": "camping",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://http2.mlstatic.com/D_NQ_NP_634214-MLB109897623162_042026-O.webp",
        "description": "MULTI-PURPOSE - Make this inverter your essential car accessories and camping accessories. Simply connect the DC battery cables directly to your 12 Volt DC battery from your car, truck, van, trailer, or RV to power your camping heater, small appliances, laptops, tablets, smartphones, gaming consoles and many other vehicle electronics.\nLED DISPLAY - Can show your battery power supply, battery input voltage, AC output voltage, output charge, overvoltage, undervoltage,overload/short circuit warning, power on/off.Uses The Control with the light display for better monitoring actual working status,convenient for you to master the power inverter working status(battery level indicator,audible alarm ).\nMULTI PROTECTION- Built-in fuses, safe charging design and cooling fan prevents the car power converter from over-heat,saving power and energy.over voltage, overload, over-current, short circuiting, under-voltage, overheating, short circuit protection.",
        "url": "https://http2.mlstatic.com/D_NQ_NP_634214-MLB109897623162_042026-O.webp",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 5
    },
    {
        "id": 1790815925173,
        "title": "فاحص اعطال TOPDON TOPSCAN Lite Pocket-Size Bluetooth Scan Tool w/Bi-Directional Controls",
        "price": "50000",
        "originalPrice": "100000",
        "currency": "د.ع",
        "category": "home",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://i.ebayimg.com/images/g/BhkAAOSwYvRnbmCR/s-l1600.webp",
        "description": "8+ Popular Functions, Full System Diagnosis: TopScan Lite supports OBD2 full system diagnosis functions, including read/clear codes, E-CU information,AUTO VIN, viewing real-time data, and active tests. It offers 8+ reset functions: Oil Reset, Throttle Adaptation, EPB Reset, Steering Angle Reset, DPF Regeneration, ABS Bleeding, BMS Reset, and SRS Reset. By these functions, you can save on unnecessary repair costs and reduce repair times significantly.\nBi-directional Control, Quickly Locate Problems: The bi-directional scan tool enables you to send commands from your smartphone directly to the vehicle's E-CU for active testing. This feature helps to quickly narrow down problem areas, such as A/C clutch, windows, doors, sunroof, etc., reducing the mechanic's diagnostic time and can help DIY users locate faults more easily. Additionally, TopScan Lite provides fault analysis and repair guidance, helping you solve problems efficiently.\nBluetooth Quick Pairing in Seconds: With the upgraded 5.0 Bluetooth system, TopScan Lite ensures a faster connection, eliminating the hassle of wires.The bluetooth pairing process needs to be completed in the application (IOS: TOPGURU&Android: TopScan). you can download our app from APP Store and Google play. TopScan Lite provides one year of free software updates.\nPerformance Testing: Always Know Your Vehicle's Condition, TopScan Lite supports speed performance testing, allowing you to analyze speed changes and calculate engine displacement efficiency,the higher the VE volumetric efficiency, the better the power output performance of the engine.\n4- Repair Guides, Your Online Assistant: TopScan Lite has launched 4 functions that are most touching for all car owners, DIY enthusiasts, and mechanics: TSB factory technical bulletins, easier and more convenient search. The OBD common fault code repair guidance, leading you to solve problems quickly. DLC diagnostic seat location, quickly positioning. Fault code database, telling you the reasons and solutions for all fault lights, saying goodbye to complicated methods.\nVehicle Coverage Lookup: Are you unsure whether the TopScan Lite scanner tool is compatible with your family's or friends' car models? We've got you covered! With the convenient TopScan Lite scanner compatible vehicle model table query function, you can easily verify compatibility with a single click. No more guesswork or uncertainty, get the answer Immediately.\nDiagnostic Tool Subscription Fee: After the first year of free updates, the subscription fee for the second year is $49.99/year for all applicable vehicle models and all features, such as system diagnostics, reset services, action tests, performance tests, repair guides, and more. You can purchase the 'Diag Bundle' to gain access for the second year, which can be done through the app. Note: You do not need to purchase the Diag Bundle in the first year, the first year is free of charge.",
        "url": "https://i.ebayimg.com/images/g/BhkAAOSwYvRnbmCR/s-l1600.webp",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 6
    },
    {
        "id": 1790815410557,
        "title": "Lando Norris McLaren MCL38 #4 4th Monaco GP Formula 1 2024 1:43 Bburago",
        "price": "25000",
        "currency": "د.ع",
        "category": "home",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://cdn.ck-modelcars.de/ck_img/ck_zoom_2k/566006/bburago_1_43_lando_norris_mclaren_mcl38_no4_4th_mo.jpg",
        "description": "4th Monaco GP Formula 1 2024 (Formula 1 World champion 2025)",
        "url": "https://cdn.ck-modelcars.de/ck_img/ck_zoom_2k/566006/bburago_1_43_lando_norris_mclaren_mcl38_no4_4th_mo.jpg",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 7
    },
    {
        "id": 1790462797558,
        "title": " كيبورد عمل جودة عالي يحمي معصمك ProtoArc EkM04 Keyboard & Mouse Ergonomic Wireless Combo Split Design Black New",
        "price": "50000",
        "originalPrice": "85000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://i.ebayimg.com/images/g/5e4AAeSwhkpp7tGl/s-l1600.webp",
        "description": "جودة عالية كيبورد و ماوس و ارقام من شركة ProtoArc \nThe ProtoArc EkM04 Keyboard & Mouse Ergonomic Wireless Combo in black features a QWERTY layout and is made of ABS plastic. With a sleek split design and ergonomic curved layout, this set provides a comfortable and efficient typing experience. The keyboard includes a separate numeric keypad, quiet scissor-switch keys, and a 2.4 GHz wireless connection. The ergonomic hard palm rest with a leather surface adds extra comfort during long hours of use. This combo set from ProtoArc offers a stylish and functional option for users looking for a reliable wireless keyboard and mouse bundle.",
        "url": "https://i.ebayimg.com/images/g/5e4AAeSwhkpp7tGl/s-l1600.webp",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 8
    },
    {
        "id": 1790462559566,
        "title": "سماعة للعمل Rownfusny R02U Wireless Headset: Bluetooth 5.3, HD Noise-Cancelling Mic, HiFi Stereo, Lightweight for PC/Phone/Zoom",
        "price": "30000",
        "originalPrice": "74000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://www.rownfusny.com/cdn/shop/files/R02U-01_2_c9b05ea7-e3ad-4844-8f35-770af9aa978d.png?v=1755738145",
        "description": "سماعة للعمل جودة مايك قوي جديدة اصلي \n\nHD ClearVoice Mic\nHi-Fi digital microphone + built-in noise reduction eliminates 90% background noise for studio-quality calls.\n\nAll-Day Comfort\nBreathable memory foam ear cushions prevent heat buildup during extended wear.\n\nInstant Dual-Mode\nSeamlessly switch between Bluetooth 5.3 and USB dongle with <40ms ultra-low latency.\n\nDual Audio Experience\nPrecision-tuned drivers deliver immersive music + crystal-clear conversations.\n\nOne-Tap Privacy\nDedicated mute button with red LED indicator for secure communications.\n\nFlash Charge\n5min charge = 70min talk time - power emergencies solved.",
        "url": "https://www.rownfusny.com/products/rownfusny-r02u-wireless-headset?_pos=1&_ss=r",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 9
    },
    {
        "id": 1789808812625,
        "title": "ملقن للموبايل و الكاميرا Teleprompter  Lensgo",
        "price": "65000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 2,
        "isSoldOut": false,
        "image": "https://m.media-amazon.com/images/I/613qJNvDJhL._AC_SL1000_.jpg",
        "description": "الحديث أمام الكاميرا بثقة تامة وسلاسة بصرية بدون نسيان أي نص! ✨\n\nهل تعاني أثناء تصوير الفيديوهات أو الدروس أونلاين من نسيان الكلمات، التلعثم، أو إبعاد نظرك عن العدسة للنظر إلى أوراق الملاحظات؟ أو تبحث عن جهاز تلقين (Teleprompter) محمول وشامل ينطوي بثانية واحدة ويقرأ النصوص بوضوح تام مع الحفاظ على الاتصال البصري مع المتابعين؟ 📱💥\n\nجهاز LENSGO TC7S المحمول مقاس 9.7 إنش هو الحل السينمائي المتكامل لصناع المحتوى، المعلمين، ومقدمي البرامج! 🚀🔥\n\nتصميم ذكي وقابل للطي يمنحك تجربة تصوير سلسة ومريحة في أي مكان:\n\n* ⏱️ طي في ثانية واحدة (One-Second Fold): تصميم مميز وسريع الطي يسهل حمل الجهاز وتخزينه داخل حقيبتك دون الحاجة لفك وتركيب المعقد.\n* 🖥️ شاشة قراءة واسعة (9.7 إنش): زجاج عالي الشفافية يتيح لك قراءة النصوص بوضوح ممتاز ومسافة قراءة مريحة بدون التأثير على جودة ونقاء صورة الكاميرا.\n* 📱 متعدد التوافق (Smartphones & Tablets): يدعم تركيب مختلف أنواع الهواتف الذكية والأجهزة اللوحية (iPads/Tablets) لإنعكاس النص، مع إمكانية التصوير باستعمال الهاتف أو الكاميرا.\n* 🎮 ريموت كنترول لاسلكي (Bluetooth Remote): يتصل بجهتك بسهولة للتحكم بزر التشغيل، التوقف، زيادة أو تقليل سرعة حركة النص بكل أريحية أثناء التصوير.\n* 📲 تطبيق خاص وسهل (Android & iOS): يعمل مع التطبيقات المخصصة للتلقين والمتاحة على المتاجر الذكية لتعديل حجم الخط وسرعة التمرير بسهولة.\n* 🎙️ منافذ تركيب إضافية (Cold Shoe Mounts): يتضمن منافذ أعلى الجهاز لتركيب ميكروفون لاسلكي أو إضاءة LED صغيرة لتجهيز استوديو محمول بالكامل.\n\nتحدث بثقة واجعل إلقاءك يبدو احترافياً وسلساً أمام الجمهور! 🎯🎬\n\nتوصيل سريع متوفر لجميع المحافظات (5,000 دينار فقط لكل العراق)! 🚚🇮🇶\n\nللطلب والاستفسار: ارسل لنا رسالة مباشرة عبر الخاص وسنتواصل معك فوراً بالتفاصيل. 📩👇\n\n***\n\nالكلمات المفتاحية والوسوم (بالعربية): 🏷️\nجهاز تلقين، تيليبرومبتر، LENSGO TC7S، جهاز قراءة النصوص، معدات تصوير، صناعة المحتوى، معدات الاستوديو، تصوير فلوغات، توصيل لكل العراق\n\n#LENSGO #Teleprompter #جهاز_تلقين #معدات_تصوير #صناعة_المحتوى #فلوغات #توصيل_لجميع_المحافظات #عراق #TechIraq\n\nEnglish Keywords & Hashtags: 🏷️📌\nLENSGO TC7S Portable Teleprompter, 9.7 Inch Foldable Teleprompter, Smartphone Teleprompter with Remote, Vlog Live Streaming Teleprompter, Online Teaching Gear, Iraq Delivery\n\n#LENSGO #Teleprompter #ContentCreatorGear #VloggingAccessories #VideoProduction #TechIraq #StudioGear",
        "url": "https://nothing.com",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 10
    },
    {
        "id": 1789809625269,
        "title": "CITYORK Mini V Mount Battery 229Wh/15500mAh 14.8V V Moun بطارية فيماونت",
        "price": "150000",
        "originalPrice": "220000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://m.media-amazon.com/images/I/71XAtedGDcL._AC_SL1500_.jpg",
        "description": "سعة طاقة عملاقة وحجم مدمج لتشغيل كادر التصوير بالكامل بدون توقف! ✨\n\nهل تعاني أثناء جولات التصوير الميداني أو التصوير الخارجي الطويل من نفاذ بطاريات الكاميرا والإضاءة بسرعة؟ أو تشيل هم حمل عدة شواحن وبطاريات مختلفة لكل جهاز في مواقع العمل؟ 🎥💥\n\nبطارية CITYORK Mini V-Mount اصلي بسعة 229Wh وهيكل مدمج هي الخيار المثالي والموثوق لتغذية كاميرتك، إضاءات الـ LED، والـ Monitor بطاقة ثابتة ومستمرة! 🚀🔥\n\nأداء استثنائي ومنافذ متعددة تلبي تطلعات المصورين وصناع الأفلام المحترفين:\n\n* ⚡ سعة هائلة وحجم مدمج (229Wh / 15500mAh / 14.8V): تقدم طاقة فائقة تشغل أجهزتك السينمائية لمدد طويلة مع الحفاظ على حجم صغير مقارنة ببطاريات الـ V-Mount التقليدية.\n* 🔌 منافذ متعددة لتغذية كل المعدات: تحتوي على منافذ D-Tap و USB-A و Type-C لتشغيل الكاميرا، المونيتور، المايكرفون، أو حتى شحن هاتفك واللابتوب بوقت واحد.\n* 📲 دعم الشحن السريع (PD Fast Charging): منفذ Type-C يدعم بروتوكولات الشحن السريع بالاتجاهين لتمكينك من إعادة شحن البطارية بسرعة وتغدي أجهزتك الذكية بكفاءة عالية.\n* 🖥️ شاشة عرض OLED ذكية: توفر قراءة دقيقة لنسبة البطارية المتبقية والفولتية في الوقت الفعلي لتكون على علم تام بوقت التشغيل المتبقي.\n* 🛡️ نظام حماية ذكي شامل: مزودة بشريحة حماية متطورة ضد الشحن الزائد، ارتفاع الحرارة، والماس الكهربائي لحماية معداتك الثمينة.\n\nاستمتع بحرية تصوير مطلق وبدون قلق من نفاذ الطاقة أثناء الإنتاج العملي! 🎯🎬\n\nتوصيل سريع متوفر لجميع المحافظات (5,000 دينار فقط لكل العراق)! 🚚🇮🇶\n\nللطلب والاستفسار: ارسل لنا رسالة مباشرة عبر الخاص وسنتواصل معك فوراً بالتفاصيل. 📩👇\n\n***\n\nالكلمات المفتاحية والوسوم (بالعربية): 🏷️\nبطارية في ماونت، سيتي يورك V Mount، بطارية CITYORK 229Wh، بطارية سينمائية، معدات تصوير، شاحن D-Tap، بطارية كاميرا احترافية، مستلزمات استوديو، توصيل لكل العراق\n\n#CITYORK #VMount #بطارية_تصوير #تصوير_سينمائي #معدات_تصوير #توصيل_لجميع_المحافظات #عراق #TechIraq\n\nEnglish Keywords & Hashtags: 🏷️📌\nCITYORK Mini V Mount Battery, 229Wh 15500mAh V Lock Battery, 14.8V D-Tap Power Bank, Cinema Camera Battery, Field Production Power, Fast Charging V-Mount, Iraq Delivery\n\n#CITYORK #VMountBattery #CinemaGear #CameraPower #FilmmakingGear #VideoProduction #TechIraq",
        "url": "https://www.amazon.es/CITYORK-Battery-15500mAh-pantalla-videoc%C3%A1mara/dp/B0DG2FKTY6",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 11
    },
    {
        "id": 1789809313238,
        "title": "K&F CONCEPT 100mm Full Color ND8 Square Filter 28 Layer Coatings Neutral Density فلتر ",
        "price": "60000",
        "originalPrice": "150000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://i.ebayimg.com/images/g/-X0AAOSweM1m2sul/s-l1600.webp",
        "description": "السيطرة الكاملة على الضوء والتقاط مشاهد طبيعية بسلاسة سينمائية وبدون أي تغيير في الألوان! ✨\n\nهل تعاني عند التصوير في أوقات النهار المشرقة من سطوع الشمس الزائد الذي يطمس تفاصيل السماء والغيوم؟ أو تحاول التقاط حركة المياه المخملية والغيوم المنسابة فتخرج صورتك بيضاء ومحتارة بالتعريض المفرط؟ 📸💥\n\nفلتر K&F Concept 100mm ND8 اصلي المربع ذو الطبقات الـ 28 المتقدمة هو الخيار الذهبي لمصوري الطبيعة واللاندسكيب للوصول إلى أعلى مستويات الدقة! 🚀🔥\n\nزجاج بصري ألماني وتقنيات طلاء متطورة تضمن لك جودة صورة فائقة:\n\n* 🛡️ طلاء احترافي من 28 طبقة (28 Layer Multi-Layer Coating): تقنية طلاء مزدوجة توفر حماية عالية ضد الخدوش، تقليل الانعكاسات المزعجة، ومقاومة الماء والزيوت لسهولة التنظيف في الميدان.\n* 🎨 عزل ضوئي دقيق (ND8 / 3-Stops): يقلل دخول الضوء بمقدار 3 محطات ضوئية، مما يتيح لك تصوير تعريض طويل (Long Exposure) وتنعيم حركة المياه والغيوم حتى تحت أشعة الشمس.\n* 💎 زجاج بصري عالي النقاء (HD Optical Glass): يحافظ على حدة ألوان المشهد الحقيقية والتفاصيل الدقيقة بدون أي انحراف في الألوان (No Color Cast).\n* 📐 قياس مربع قياسي (100x100mm): بسُمك 2mm مطابِق لأغلب أنظمة الحوامل المربعة (100mm Square Filter Holders) لسرعة التركيب والتبديل مقارنة بالفلاتر الدائرية.\n* 🎒 حافظة جلدية فاخرة: تأتي مع جُراب حماية متين ومبطن لحماية الفلتر من الصدمات والغبار أثناء التنقل والرحلات.\n\nالتقط صوراً احترافية بتعريض متوازن وتأثيرات سينمائية تأسر الأبصار! 🎯🌅\n\nتوصيل سريع متوفر لجميع المحافظات (5,000 دينار فقط لكل العراق)! 🚚🇮🇶\n\nللطلب والاستفسار: ارسل لنا رسالة مباشرة عبر الخاص وسنتواصل معك فوراً بالتفاصيل. 📩👇\n\n***\n\nالكلمات المفتاحية والوسوم (بالعربية): 🏷️\nفلتر ND8 مربع، كي اند إف كونسبت، فلتر 100 مم، فلاتر تصوير لاندسكيب، فلاتر عدسات احترافية، معدات تصوير، تصوير تعريض طويل، KF Concept العراق، توصيل لكل العراق\n\n#KFConcept #فلتر_مربع #تصوير_لاندسكيب #معدات_تصوير #فلاتر_عدسات #توصيل_لجميع_المحافظات #عراق #TechIraq\n\nEnglish Keywords & Hashtags: 🏷️📌\nKF Concept 100mm ND8 Square Filter, 28 Layer Coating Neutral Density Filter, 100x100mm Optical Glass ND Filter, Landscape Photography Gear, Long Exposure Square Filter, Iraq Delivery\n\n#KFConcept #ND8Filter #SquareFilter #LandscapePhotography #LongExposure #CameraAccessories #TechIraq",
        "url": "https://www.ebay.com/itm/166957304415",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 12
    },
    {
        "id": 1789809181784,
        "title": "R075 Wooden Handle Grip Left Right قبضة تصوير Ulanzi ",
        "price": "35000",
        "originalPrice": "100000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 2,
        "isSoldOut": false,
        "image": "https://m.media-amazon.com/images/I/71EDXhLZ4cL._SL1500_.jpg",
        "description": "التحكم الكامل والراحة الفائقة أثناء تصوير الفيديوهات الطويلة بلمسة خشبية كلاسيكية! ✨\n\nهل تعاني أثناء تصوير الفيديوهات المحمولة باليد من اهتزاز الكاميرا، أو صعوبة التثبيت وإرهاق اليد عند التصوير لفترات طويلة؟ أو تبحث عن مقبض جانبي مريح ومصمم من الخشب الطبيعي يمنحك ثباتاً سينمائياً ومظهراً احترافياً لعدتك؟ 🎥💥\n\nمقبض Ulanzi R075 اصلي الخشبي المزدوج (يمين/يسار) هو الإضافة المثالية لكيج الكاميرا (Camera Cage) للارتقاء بثبات تصويرك ومستوى احترافيتك! 🚀🔥\n\nتصميم مريح وتوافق عالي يضمن لك أعلى مستويات التحكم والسهولة:\n\n* 🪵 خشب جوز طبيعي فاخر (Natural Walnut Wood): مصمم بحواف منحنية تتطابق مع راحة اليد لمنحك قبضة دافئة ومريحة تمنع الانزلاق وتخفف الإجهاد أثناء التصوير الميداني.\n* 🔄 تصميم مزدوج ذكي (Left & Right Universal): يمكن تعديله وتركيبه بسهولة على الجانب الأيمن أو الأيسر لقفص الكاميرا حسب رغبتك وطريقة تصويرك.\n* 📐 تعديل الارتفاع مرن: يتيح لك ضبط الارتفاع الرأسي للمقبض بسهولة لتناسب توازن العدسة ومركز ثقل الكاميرا.\n* 🔒 تثبيت محكم وبسيط (Arri Rosette / NATO / 1/4\"-20): يركب بسرعة وأمان على غالبية أقفاص الكاميرات عبر برغي تثبيت محكم يمنع أي اهتزاز.\n* 🎙️ منافذ تركيب إضافية (Cold Shoe & Threaded Holes): مزود بفتحة Cold Shoe علوية مع فتحات برغي 1/4\"-20 لتركيب ميكروفون لاسلكي، شاشة Monitor، أو إضاءة LED صغيرة بكل سهولة.\n* 🛠️ مفتاح ألن مدمج (Built-in Allen Wrench): يحتوي على مفتاح ربط مغناطيسي مخفي في الجزء السفلي للمقبض لتعديل وشد البرغي في أي وقت بدون البحث عن أدوات خارجية.\n\nاحصل على ثبات سينمائي وراحة تامة لمشروعاتك السينمائية والفيديوهات اليومية! 🎯🎬\n\nتوصيل سريع متوفر لجميع المحافظات (5,000 دينار فقط لكل العراق)! 🚚🇮🇶\n\nللطلب والاستفسار: ارسل لنا رسالة مباشرة عبر الخاص وسنتواصل معك فوراً بالتفاصيل. 📩👇\n\n***\n\nالكلمات المفتاحية والوسوم (بالعربية): 🏷️\nمقبض خشب كاميرا، اولانزي R075، Ulanzi R075، مقبض جانبي كيج، اكسسوارات كاميرات، معدات تصوير سينمائي، قبضة كاميرا خشبي، كيج اولانزي، توصيل لكل العراق\n\n#Ulanzi #UlanziR075 #مقبض_كاميرا #معدات_تصوير #تصوير_سينمائي #صناعة_المحتوى #توصيل_لجميع_المحافظات #عراق #TechIraq\n\nEnglish Keywords & Hashtags: 🏷️📌\nUlanzi R075 Wooden Handle Grip, Universal Side Handle for Camera Cage, Left Right Wooden Grip, Wooden Camera Rig Accessories, Cold Shoe Mount Handle, Videography Handgrip, Iraq Delivery\n\n#Ulanzi #UlanziR075 #CameraRig #CameraCage #FilmmakingGear #VideographyAccessories #TechIraq",
        "url": "https://m.media-amazon.com/images/I/71EDXhLZ4cL._SL1500_.jpg",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 13
    },
    {
        "id": 1779378765389,
        "title": "Mormaii FLEXXXA SLIM Professional Beach Tennis Paddle",
        "price": "60000",
        "originalPrice": "280000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://iambeachtennis.com/cdn/shop/products/iambeachtennis_mormaii-beach-tennis_raquete-mormaii-flexxxa-slim-professional-advanced-beach-tennis-paddle.jpg?v=1671253238",
        "description": "مضرب Mormaii FLEXXXA 2022.. السلاح السري للمحترفين في ملاعب الـ Beach Tennis\n\n🔴 تطور واحترافية: هذا المضرب مو مجرد أداة، هذا \"Flexxxa\" إصدار 2022 المصمم خصيصاً للاعبين المحترفين والمتقدمين اللي يدورون على دمج مثالي بين القوة والتحكم، ويخليك تسيطر على كل ضربة بالملعب بثقة مطلقة.\n\n⭕ هيكل كاربوني متين: المضرب مصنوع بالكامل من الكاربون 3K (الفريم والوجه)، وهذا الشي يعطيك مرونة عالية جداً وقوة دفع خرافية للكرة، وبنفس الوقت يحافظ على استقرار المضرب حتى وية أقوى الضربات.\n\n✅ مواصفات \"توب\" للآداء العالي:\n\nالقلب: حشوة EVA Soft اللي تمتص الصدمات وتعطيك شعور مريح جداً بالإيد وتساعدك بضربات دقيقة ومتحكم بها.\n\nالسطح: يتميز بـ 32 ثقب مع سطح خشن يساعدك بزيادة \"السبين\" (Spin) والسيطرة على مسار الكرة.\n\nالوزن والمقاس: وزن مثالي (حوالي 330 غرام) وطول 50 سم، يعني خفة بالحركة وسرعة استجابة مذهلة وقت التبادل السريع.\n\n🟩 تصميم يريحك بالمباريات: المضرب متوازن جداً ويقلل من تعب الإيد حتى بالمباريات الطويلة والمجهدة، ويجي وياه \"كفر\" (حقيبة) أصلية تحمي المضرب من الخدوش والأوساخ بعد كل طلعة.\n\n🟢 ماركة غنية عن التعريف: Mormaii هي الملكة بمجال الـ Beach Tennis، وكل قطعة من إصداراتهم هي استثمار بمعداتك الرياضية لتعيش وياك عمر وتتحمل أصعب ظروف اللعب على الرمل.\n\n🟥 الكمية محدودة: إذا تريد تنقل مستواك لمرحلة الاحتراف وتلعب بمضرب بطل، لا تتردد. اتصل بينا أو راسلنا على الخاص واحجز قطعتك قبل لا تخلص الوجبة، والتوصيل مالتنا سريع ويوصلك لكل مكان بالعراق وتدلل علينا!\n\nMormaii FLEXXXA 2022 Professional Beach Tennis Racket\nڕاکێتی تێنسی کەنار دەریا مۆرمای فلێکسا ٢٠٢٢",
        "url": "https://iambeachtennis.com/products/mormaii-flexxxa-slim-2022-professional-beach-tennis-paddle?_su_rec=YEgJ4E2yE48SlPAeagYp_u0gIRlcUx6MJhlcOvcMhqco85rzeowuSzGGcTyNucPdgnEec6EZzlPn1bFDzcevb_VSg05aElwJUlJVnll3aDgCjMz_VQPSVlmnG4tUrNKdSp5CRvUYnK9-ZxGoM8NsYr-DVxyaBds5EumZdUlM5U5JcgS1Kdig7-vyVGmpfmWleAVvAvZivlY6xZ7gsy7lvmrhBwtbhjmIJXgshDwpXed1byqsWdN3nZ4GnDTo4e9lbaZNaRviWJInRsa_23I0kNJQCyiWPJcsxjkFYNql1RXV72nYrRs&_su_rec_id=7b736abc-c9b4-4811-88cb-af3356671570-1779378627",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 14
    },
    {
        "id": 1790878732474,
        "title": "Keychron b6 pro keyboard كيبورد جودة عالية للماك ",
        "price": "45000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://www.keychron.com/cdn/shop/files/B6-Pro-Iconic-Features.jpg?v=1761279632&width=1000",
        "description": "لوحة المفاتيح Keychron B6 Pro هي كيبورد لاسلكي فائق النحافة وكامل الحجم مصمم خصيصاً للإنتاجية والعمل المكتبي الهادئ.\nالمواصفات الرئيسية\n• الحجم والتصميم: كامل الحجم (100% مع لوحة أرقام Numpad)، بتخطيط يضم 109 مفتاحاً، وبتصميم فائق النحافة.\n• خيارات الاتصال: يدعم 3 طرق للاتصال (لاسلكي 2.4 جيجاهرتز، بلوتوث 5.2، وسلكي عبر كابل USB Type-C).\n• معدل الاستطلاع (Polling Rate): يصل إلى 1000 هرتز في وضع 2.4GHz والوضع السلكي، و100 هرتز في وضع البلوتوث.\n• عمر البطارية: بطارية بسعة 800 أمبير/ساعة توفر ما يصل إلى 1200 ساعة من الاستخدام المتواصل، مع منفذ شحن USB-C.\n• التوافق والبرمجيات: متوافق بسلاسة مع أنظمة تشغيل Windows و macOS و iOS، ويدعم التخصيص وإعادة تعيين المفاتيح عبر تطبيق الويب [Keychron Launcher] دون الحاجة لتثبيت برامج دائمية.\n• نوع المفاتيح: مفاتيح مقصية (Scissor switches) هادئة ومريحة للكتابة الطويلة.",
        "url": "https://www.keychron.com/cdn/shop/files/B6-Pro-Iconic-Features.jpg?v=1761279632&width=1000",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 15
    },
    {
        "id": 1779378489358,
        "title": "ULANZI Claw Quick Release Camera Mount",
        "price": "25000",
        "originalPrice": "50000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 3,
        "isSoldOut": false,
        "image": "https://m.media-amazon.com/images/I/612DnCX6kKL._AC_SL1200_.jpg",
        "description": "🔴 فك وتركيب بلمحة عين: وداعاً لهوسة البراغي اللي تاخذ وكت وتضيع اللقطة؛ هذا النظام يخليك تفك وتشد الكاميرا من الترايبود بضغطة وحدة، يعني سرعة وانسيابية ما إلها مثيل.\n\n⭕ قفل أمان وموثوق: التصميم مالته عبقري، يربط الكاميرا أو الجيمبل بكل ثبات بفضل نظام \"السلايد لوك\" (Slide Lock). القفل ماله متين ويخليك تشتغل وأنت مرتاح ومطمن إن الكاميرا مأمنة بمكانها وما تتحرك.\n\n✅ يرهم على كل شي: الماونت عالمي ومصمم ليشتغل وية أي كاميرا عندك. يعني التنقل بين الترايبود، الجيمبل، أو أي ستاند ثاني صار أسهل وأسرع من أي وكت مضى.\n\n🟩 خفيف وذكي: حجمه كلش صغير (40 ملم) ووزنه بس 50 غرام، يعني ما يضيف أي ثقل على معداتك. ومزود بـ \"ربل\" ناعم يحمي الكاميرا من الخدوش ويمنع الانزلاق.\n\n🟢 قوة تحمل جبارة: مصنوع من ألمنيوم صلب يتحمل وزن لحد 50 كيلو! يعني انسى البلاستيك والكسر، هاي القطعة تعيش وياك عمر وتتحمل أكرف ظروف الشغل.\n\n🟥 وصلت الوجبة الجديدة يمنا: لا تضيع وقتك بالتركيب اليدوي وتطور معداتك هسة. اتصل بينا أو راسلنا على الخاص واحجز قطعتك قبل لا تخلص، التوصيل مالتنا سريع ويوصلك وين ما جنت بالعراق وتدلل!\n\nULANZI Claw Quick Release Plate\nیوڵانزی کڵاو کویک ڕیلیس پڵەیت",
        "url": "https://www.amazon.co.uk/ULANZI-Release-Adapter-Cameras-Monopod/dp/B08CGN3L6F",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 16
    },
    {
        "id": 1777149291882,
        "title": "LOFREE keyboard  flow lite 84",
        "price": "80000",
        "originalPrice": "186000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://www.lofree.co/cdn/shop/files/Flow84_White_PI03.webp?v=1727493654&width=800",
        "description": "Lofree Flow Lite 84 - الأناقة البيضاء في متناول يدك ⌨️✨\nأهم المميزات باختصار ⚡\nتصميم فائق النحافة: لوحة ميكانيكية (Low-Profile) تجمع بين الأناقة والراحة لمعصم اليد 💎.\nأنعم تجربة طباعة: بفضل سويتشات Specter POM التي تزداد نعومة مع كل ضغطة ☁️.\nزر الإيموجي السريع: عبّر عن مشاعرك بضغطة زر واحدة مخصصة للرموز التعبيرية 😍.\nصوت هادئ وممتع: تقنية Gasket Mount تمنحك صوتاً \"ثقياً\" وناعماً بدون ضجيج 🔊.\nتحكم كامل: بكرة ميكانيكية أنيقة للتحكم السريع في مستوى الصوت 🔄.\nالمواصفات التقنية 🛠️\nاللون: أبيض لؤلؤي (Off-white) مع لمسات رمادية فاتحة ⚪.\nعدد المفاتيح: 84 مفتاحاً (توزيع 75%) لتوفير مساحة المكتب 📏.\nنوع الاتصال: ثلاثي الأوضاع (بلوتوث 5.4، لاسلكي 2.4G، سلكي USB-C) 📶.\nسرعة الاستجابة: 1000Hz (في وضع اللاسلكي 2.4G) للأداء السريع 🚀.\nالتوافق: تدعم أنظمة (Windows, macOS, iOS, Android) مع سهولة التبديل 💻📱.\nالبطارية: سعة 2000mAh تدوم طويلاً مع منفذ شحن سريع 🔋.\nالإضاءة: إضاءة خلفية LED بيضاء هادئة قابلة للتعديل 💡.\nالمواد: مفاتيح PBT عالية الجودة مقاومة للتآكل واللمعان ⌨️.",
        "url": "https://www.lofree.co/products/flow-lite84-mechanical-keyboard#:~:text=The%20Flow%20Lite84%20is%20designed,Satisfying%20Acoustics.",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 17
    },
    {
        "id": 1777148744013,
        "title": "Nike air force black 44 size",
        "price": "50000",
        "currency": "د.ع",
        "category": "clothing",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://static.nike.com/a/images/t_web_pdp_535_v2/f_auto,u_9ddf04c7-2a9a-4d76-add1-d15af8f0263d,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/fc4622c4-2769-4665-aa6e-42c974a7705e/AIR+FORCE+1+%2707.png",
        "description": "نايكي إير فورس 1 \"أسود بالكامل\" (Triple Black)\nالأناقة الكلاسيكية التي لا تنتهي.\nالتصميم: جلد طبيعي فاخر بالكامل، يجمع بين القوة والمظهر العصري.\nالراحة: مزود بتقنية Nike Air لتوسيد مريح يدوم طوال اليوم.\nالمتانة: نعل مطاطي قوي يوفر ثباتاً ممتازاً على مختلف الأسطح.\nالمقاس: 44 EU (مثالي لمن يبحث عن مظهر رياضي مريح).\nالاستخدام: قطعة أساسية تناسب جميع الإطلالات (سبورت، جينز، كاجوال).\nحذاء واحد.. لكل المناسبات.",
        "url": "https://www.nike.com/t/air-force-1-07-mens-shoes-jBrhbr/CW2288-001",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "sortOrder": 18,
        "originalPrice": "178000"
    },
    {
        "id": 1776611968243,
        "title": "Meike lens adapter EF - EOS R 0.71 X",
        "price": "120000",
        "originalPrice": "353400",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://meikeglobal.com/cdn/shop/files/B29A7949.png?v=1717129704&width=1985",
        "description": "محول عدسة افضل من الاصلي أهم مميزات محول Meike 0.71x Locking في نقاط مختصرة:\nزيادة الإضاءة: يمنحك وقفة ضوئية إضافية (مثلاً تتحول f/4 إلى f/2.8).\nتوسيع الزاوية: يقلل البعد البؤري بمقدار 0.71x لتعويض \"الكروب سنسور\".\nقفل سينمائي: نظام تثبيت دوار يمنع اهتزاز العدسة نهائياً (Zero Play).\nجودة بصرية: يحتوي على 5 عناصر زجاجية لتركيز الضوء على الحساس.\nمتانة المعدن: تصميم قوي من الفولاذ المقاوم للصدأ مع حماية من الطقس.\nدعم إلكتروني: نقل كامل لبيانات الـ EXIF ودعم الفوكس التلقائي (AF).",
        "url": "https://meikeglobal.com/products/speedbooster?variant=44212080804068",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 19
    },
    {
        "id": 1776611664989,
        "title": "Quntis Monitor Light Bar Focus Black, PRO+",
        "price": "50000",
        "originalPrice": "120000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://www.quntis.com/cdn/shop/files/31279278096450.jpg?v=1710310541&width=1000",
        "description": "مصباح Quntis Monitor Light Bar PRO+ (51 سم) هو حل إضاءة احترافي يتميز بـ:\nتصميم ذكي: يتناسب مع الشاشات المسطحة والمنحنية، مع ريموت كنترول لاسلكي للتحكم السهل.\nحماية العين: تقنية تمنع الوهج وانعكاس الضوء على الشاشة، مما يقلل إجهاد العين.\nتحكم ذكي: مستشعر مدمج للتعتيم التلقائي حسب إضاءة الغرفة، مع إمكانية تعديل السطوع ودرجة اللون يدوياً.\nمثالي للعمل والألعاب: يوفر إضاءة مكتبية مركزة توفر مساحة على الطاولة بفضل التصميم المعلق.",
        "url": "https://www.quntis.com/products/monitor-light-bar-pro-with-remote-control-eye-care-technology-computer-monitor-lamp-with-auto-dimming-no-screen-glare",
        "condition": "new",
        "featured": false,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 20
    },
    {
        "id": 1776611502245,
        "title": "Mella ساعة ذكية لتعليم وقت النوم للاطفال",
        "price": "15000",
        "originalPrice": "77500",
        "currency": "د.ع",
        "category": "home",
        "quantity": 1,
        "isSoldOut": false,
        "image": "https://littlehippo.com/cdn/shop/files/Pink-bluegreen-light_edit_2048x.jpg?v=1729104363",
        "description": "ميلا (Mella) من Little Hippo هي ساعة تدريب ذكية ومضيئة للأطفال، صُممت لتحسين عادات النوم.\nالمزايا:\nمؤشر ضوئي: ألوان تعليمية (أحمر للنوم، أصفر للاستعداد، أخضر للاستيقاظ).\nوقت القيلولة: إعدادات مخصصة للقيلولة.\nأصوات مهدئة: تحتوي على أصوات طبيعية وموسيقى هادئة.\nشاشة رقمية: واجهة بسيطة لتعلم الوقت.\nخاصية قفل الأمان: لمنع الأطفال من تغيير الإعدادات.\nتساعد طفلك على معرفة وقت النوم والنهوض بشكل ممتع وآمن.",
        "url": "https://littlehippo.com/products/mella",
        "condition": "new",
        "featured": true,
        "isDemo": false,
        "noCrop": false,
        "sortOrder": 21
    },
    {
        "id": 10,
        "title": "مصباح مكتبي ذكي",
        "price": "40000",
        "currency": "د.ع",
        "category": "home",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80",
        "description": "مصباح مكتب بإضاءة قابلة للتعديل والتحكم باللمس، مريح للعين.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 22,
        "originalPrice": "50000"
    },
    {
        "id": 7,
        "title": "حقيبة ظهر للسفر",
        "price": "45000",
        "currency": "د.ع",
        "category": "clothing",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        "description": "حقيبة متينة ومقاومة للماء، مع مساحة مخصصة للكمبيوتر المحمول.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 23,
        "originalPrice": "55000"
    },
    {
        "id": 5,
        "title": "لوحة مفاتيح ميكانيكية",
        "price": "65000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
        "description": "لوحة مفاتيح بإضاءة RGB، مفاتيح زرقاء سريعة الاستجابة.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 24,
        "originalPrice": "80000"
    },
    {
        "id": 4,
        "title": "شاشة كمبيوتر 27 بوصة",
        "price": "210000",
        "currency": "د.ع",
        "category": "pc",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
        "description": "شاشة عالية الدقة 144Hz، ألوان زاهية، مثالية للألعاب والإنتاجية.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 25,
        "originalPrice": "250000"
    },
    {
        "id": 3,
        "title": "حذاء رياضي للجري",
        "price": "85000",
        "currency": "د.ع",
        "category": "clothing",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
        "description": "حذاء مريح وخفيف الوزن، مصمم خصيصاً للجري والمسافات الطويلة.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 26,
        "originalPrice": "100000"
    },
    {
        "id": 2,
        "title": "خيمة تخييم عائلية",
        "price": "120000",
        "currency": "د.ع",
        "category": "camping",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=600&q=80",
        "description": "خيمة واسعة تتسع لـ 4 أشخاص، مقاومة للماء والرياح، سهلة التركيب.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 27,
        "originalPrice": "150000"
    },
    {
        "id": 1,
        "title": "كاميرا رقمية احترافية",
        "price": "450000",
        "currency": "د.ع",
        "category": "photography",
        "quantity": 0,
        "isSoldOut": true,
        "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80",
        "description": "كاميرا احترافية بدقة 4K مع عدسة 50mm، مثالية للمصورين المحترفين والمبتدئين.",
        "url": "https://amazon.com",
        "condition": "new",
        "featured": false,
        "isDemo": true,
        "sortOrder": 28,
        "originalPrice": "500000"
    }
];
